version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci

  build:
    commands:
      - sam build

artifacts:
  files:
    - .aws-sam/**/*
    - template.yaml
