version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - npm ci

  build:
    commands:
      - sam build

artifacts:
  files:
    - '**/*'
  base-directory: .aws-sam/build
